In [40]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [41]:
ficheros=[]
datos=[]

In [42]:
with open("software/salidas/localSearch2.txt",'r') as f:
    lines= f.readlines()

lines=lines[1:]

i=0
while i < len(lines):
    ficheros.append(lines[i].replace('data/','').replace('\n',''))
    datos.append(int(list(map(float,lines[i+1].split('\t')))[2]))
    i+=2

In [43]:
datos

[22500,
 19800,
 22050,
 22050,
 24300,
 16200,
 16650,
 22950,
 17100,
 20700,
 100800,
 100800,
 100800,
 100800,
 100800,
 100800,
 100800,
 100800,
 100800,
 100800,
 101400,
 100000,
 100000,
 100000,
 100800,
 102600,
 100800,
 102600,
 101400,
 101400]

In [44]:
df = pd.DataFrame({'File':[],'Calls':[]})

In [45]:
for i in range(len(ficheros)):
    new_row={'File':ficheros[i][:-4],'Calls':datos[i]}
    df=df.append(new_row, ignore_index=True)

In [46]:
df.index=df.File
df.drop(columns=['File'],inplace=True)

In [47]:
df

                        Calls
File
MDG-a_10_n500_m50     22500.0
MDG-a_1_n500_m50      19800.0
MDG-a_2_n500_m50      22050.0
MDG-a_3_n500_m50      22050.0
MDG-a_4_n500_m50      24300.0
MDG-a_5_n500_m50      16200.0
MDG-a_6_n500_m50      16650.0
MDG-a_7_n500_m50      22950.0
MDG-a_8_n500_m50      17100.0
MDG-a_9_n500_m50      20700.0
MDG-b_21_n2000_m200  100800.0
MDG-b_22_n2000_m200  100800.0
MDG-b_23_n2000_m200  100800.0
MDG-b_24_n2000_m200  100800.0
MDG-b_25_n2000_m200  100800.0
MDG-b_26_n2000_m200  100800.0
MDG-b_27_n2000_m200  100800.0
MDG-b_28_n2000_m200  100800.0
MDG-b_29_n2000_m200  100800.0
MDG-b_30_n2000_m200  100800.0
MDG-c_10_n3000_m400  101400.0
MDG-c_13_n3000_m500  100000.0
MDG-c_14_n3000_m500  100000.0
MDG-c_15_n3000_m500  100000.0
MDG-c_19_n3000_m600  100800.0
MDG-c_1_n3000_m300   102600.0
MDG-c_20_n3000_m600  100800.0
MDG-c_2_n3000_m300   102600.0
MDG-c_8_n3000_m400   101400.0
MDG-c_9_n3000_m400   101400.0

In [48]:
#df.to_csv('results/localSearch.csv')
#df.to_csv('results/localSearch2.csv')
#df.to_csv('results/greedy.csv')
df.to_csv('results/LS2-calls.csv')